"""Binary distillation by the McCabe–Thiele method.

Builds the operating lines and steps off theoretical stages against the **real
equilibrium curve** generated by an activity model (not a constant relative
volatility), so azeotropic behaviour and curvature are captured correctly.

Construction (light component, mole fractions):

* Equilibrium curve  y*(x)  — bubble-point sweep at the column pressure.
* Rectifying operating line (ROL):  y = R/(R+1) · x + x_D/(R+1)
* q-line (feed):  y = q/(q−1) · x − z_F/(q−1)   (vertical x = z_F when q = 1)
* Stripping operating line (SOL): through (x_B, x_B) and the ROL∩q-line point.
* Minimum reflux from the q-line∩equilibrium pinch.

Stages are stepped from (x_D, x_D): alternate horizontal moves to the
equilibrium curve and vertical moves to the operating line (ROL above the feed
pinch, SOL below). The partial reboiler counts as one equilibrium stage.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.optimize import brentq

from .models.vle import ThermodynamicModel


class DistillationError(ValueError):
    """Invalid distillation specification."""


@dataclass
class McCabeThieleResult:
    x_eq: np.ndarray
    y_eq: np.ndarray
    z_F: float
    q: float
    R: float
    x_D: float
    x_B: float
    pressure_mmHg: float
    intersection: tuple[float, float]   # ROL ∩ q-line
    pinch: tuple[float, float]          # q-line ∩ equilibrium
    R_min: float
    steps: list[tuple[float, float]]    # staircase vertices
    stage_corners: list[tuple[float, float]]  # equilibrium-curve corners (one per stage)
    n_stages: int                       # theoretical stages incl. reboiler
    feed_stage: int
    feasible: bool
    message: str = ""

    @property
    def n_trays(self) -> int:
        return max(self.n_stages - 1, 0)  # column trays (reboiler excluded)

    @property
    def reflux_ratio_to_min(self) -> float:
        return self.R / self.R_min if self.R_min > 0 else float("inf")

    def rol(self, x):
        return self.R / (self.R + 1.0) * x + self.x_D / (self.R + 1.0)

    def sol(self, x):
        xi, yi = self.intersection
        m = (yi - self.x_B) / (xi - self.x_B)
        return self.x_B + m * (x - self.x_B)

    def q_line(self, x):
        if abs(self.q - 1.0) < 1e-9:
            return np.full_like(np.asarray(x, dtype=float), np.nan)
        return self.q / (self.q - 1.0) * x - self.z_F / (self.q - 1.0)


def equilibrium_curve(model: ThermodynamicModel, pressure_mmHg: float = 760.0,
                      n: int = 201) -> tuple[np.ndarray, np.ndarray]:
    """Light-component x–y equilibrium curve at the column pressure."""
    x = np.linspace(0.0, 1.0, n)
    y = np.empty(n)
    for i, xi in enumerate(x):
        _, yv = model.bubble_temperature([xi, 1.0 - xi], pressure_mmHg, "mmHg", "Celsius")
        y[i] = yv[0]
    return x, y


def _intersection_rol_qline(R, x_D, q, z_F):
    a, b = R / (R + 1.0), x_D / (R + 1.0)        # ROL: y = a x + b
    if abs(q - 1.0) < 1e-9:                        # vertical q-line at x = z_F
        return z_F, a * z_F + b
    sq, bq = q / (q - 1.0), -z_F / (q - 1.0)      # q-line: y = sq x + bq
    xi = (b - bq) / (sq - a)
    return xi, a * xi + b


def minimum_reflux(model_eq, x_D, z_F, q, x_B, pressure=None):
    """R_min from the pinch where the q-line meets the equilibrium curve."""
    x_eq, y_eq = model_eq
    yx = lambda x: np.interp(x, x_eq, y_eq)
    if abs(q - 1.0) < 1e-9:
        x_p = z_F
    else:
        sq, bq = q / (q - 1.0), -z_F / (q - 1.0)
        f = lambda x: yx(x) - (sq * x + bq)
        lo, hi = max(x_B, 1e-4), min(x_D, 1.0 - 1e-4)
        x_p = brentq(f, lo, hi) if f(lo) * f(hi) < 0 else z_F
    y_p = float(yx(x_p))
    slope = (x_D - y_p) / (x_D - x_p)
    r_min = slope / (1.0 - slope)
    return float(r_min), (float(x_p), y_p)


def mccabe_thiele(model: ThermodynamicModel, z_F: float, q: float, R: float,
                  x_D: float, x_B: float, pressure_mmHg: float = 760.0,
                  n_eq: int = 201, max_stages: int = 200) -> McCabeThieleResult:
    if not (0.0 < x_B < z_F < x_D < 1.0):
        raise DistillationError(
            "Require 0 < x_B < z_F < x_D < 1 (light-component mole fractions).")
    if R <= 0:
        raise DistillationError("Reflux ratio must be positive.")

    x_eq, y_eq = equilibrium_curve(model, pressure_mmHg, n_eq)
    yx = lambda x: float(np.interp(x, x_eq, y_eq))
    xy = lambda y: float(np.interp(y, y_eq, x_eq))   # y_eq is monotonic increasing

    r_min, pinch = minimum_reflux((x_eq, y_eq), x_D, z_F, q, x_B)
    xi, yi = _intersection_rol_qline(R, x_D, q, z_F)

    rol = lambda x: R / (R + 1.0) * x + x_D / (R + 1.0)
    m_sol = (yi - x_B) / (xi - x_B)
    sol = lambda x: x_B + m_sol * (x - x_B)

    feasible = R > r_min
    message = "" if feasible else (
        f"Reflux ratio R = {R:.3f} is below the minimum R_min = {r_min:.3f}; "
        "the column would need infinite stages (pinch).")

    # Step off stages from the top.
    steps: list[tuple[float, float]] = [(x_D, x_D)]
    corners: list[tuple[float, float]] = []
    x, y = x_D, x_D
    n = 0
    feed_stage = None
    while x > x_B and n < max_stages:
        n += 1
        x = xy(y)                       # horizontal → equilibrium curve
        steps.append((x, y))
        corners.append((x, y))
        if x <= x_B:
            break
        if x >= xi:                     # vertical → operating line
            y = rol(x)
        else:
            if feed_stage is None:
                feed_stage = n
            y = sol(x)
        steps.append((x, y))

    converged = n < max_stages
    if not converged:
        feasible = False
        message = message or "Did not converge — check specifications (pinch/azeotrope)."
    if feed_stage is None:
        feed_stage = n

    return McCabeThieleResult(
        x_eq=x_eq, y_eq=y_eq, z_F=z_F, q=q, R=R, x_D=x_D, x_B=x_B,
        pressure_mmHg=pressure_mmHg, intersection=(xi, yi), pinch=pinch,
        R_min=r_min, steps=steps, stage_corners=corners, n_stages=n,
        feed_stage=feed_stage, feasible=feasible, message=message,
    )
